apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        config.version: "{{ .Chart.Version }}"
        build.timestamp: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        
        # Environment variables from ConfigMap
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: APP_NAME
        - name: DEPLOYMENT_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: DEPLOYMENT_ENVIRONMENT
        
        # Volume mounts for ConfigMap files
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      
      # Volumes definition
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config
          defaultMode: 0644